### PR TITLE
Allow dependent applications to programmatically set the current index

### PR DESCRIPTION
**Pull request by DrakeXorn**
### Description

As requested in #300 (and also because I needed it 😄), this implements a simple `useEffect` that updates `activeTimelineIndex` with `activeItemIndex`'s value on prop update.

### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/prabhuignoto/react-chrono/blob/master/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Review by prabhuignoto — APPROVED** [review]
LGTM

**Comment by prabhuignoto** [comment]
@all-contributors please add @DrakeXorn for code

**Comment by joshAntoniuk** [comment]
Are you able to detail how to use this feature ? I have a swiper with its own controls and want it to control the timeline as well!

**Comment by DrakeXorn** [comment]
Hey @joshAntoniuk !
You can just use a simple index state variable and pass it to the library as `activeTimelineIndex`.

As an example, here is the getting started code (found in the README) adapted with my change:
```tsx
import React from "react"
import { Chrono } from "react-chrono";

const Home = () => {
  const [itemIndex, setItemIndex] = React.useState<number>(0);
  const items = [{
    title: "May 1940",
    cardTitle: "Dunkirk",
    url: "http://www.history.com",
    cardSubtitle:"Men of the British Expeditionary Force (BEF) wade out to..",
    cardDetailedText: "Men of the British Expeditionary Force (BEF) wade out to..",
    media: {
      type: "IMAGE",
      source: {
      url: "http://someurl/image.jpg"
      }
    }
  }, ...];

  const incrementIndex = () => {
    if (itemIndex < items.length - 1) {
      setItemIndex(itemIndex + 1);
    }
  };

  const decrementIndex = () => {
    if (itemIndex > 0) {
      setItemIndex(itemIndex - 1);
    }
  };
  
  return (
    <>
      <div>
        <button onClick={decrementIndex}>Previous</button>
        <span>Current index: {itemIndex + 1}</span>
        <button onClick={incrementIndex}>Next</button>
      </div>
      <div style={{ width: "500px", height: "400px" }}>
        <Chrono items={items} activeTimelineIndex={itemIndex} />
      </div>
    </>
  );
}
```

Hope this helps 😄

**Comment by joshAntoniuk** [comment]
Hm. I appreciate the help, but it doesn't seem to work for me. Here's my code:

```
const [timelineIndex, setTimelindeIndex] = useState(0);
<Chrono
            hideControls={true}
            theme={{
              titleColor: '#262626',
              titleColorActive: '#262626',
              primary: '#CECECE',
              secondary: '#e71d21',
            }}
            activeTimelineIndex={timelineIndex}
            items={sortArray()}
            mode="HORIZONTAL"
          />

<div className="flex w-full flex-row items-end justify-end gap-x-10 pr-8">
            <Button
              form={true}
              style="text"
              size="smaller"
              icon="back"
              onClick={() => {
                swiperRef.current.slidePrev();
                decrementIndex();
              }}
              className="flex-row-reverse"
            >
              Back
            </Button>
            <Button
              form={true}
              style="text"
              size="smaller"
              icon="forward"
              onClick={() => {
                swiperRef.current.slideNext();
                incrementIndex();
                console.log(timelineIndex);
              }}
            >
              Forward
            </Button>
          </div>
```

**Pull request merged**
