### PR TITLE
Showing all cards in horizontal mode

### PR DESCRIPTION
**Pull request by rawandeheliah**
### Description

This PR is to enhance timeline in horizontal mode:  by showing all cards in horizontal mode.
Old scenario:  only one card is shown all the time , which is the selected one . 

To try this feature : all you have to do is to pass: `showAllCards={true}`  as a prop to ` Chrono` component.

### Final Result: 

Screen Shot 2021-12-19 at 11 28 42

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

-solves [issue #196 ](https://github.com/prabhuignoto/react-chrono/issues/196)

### CODE REVIEW

**Comment by prabhuignoto** [comment]
@rawandeheliah thanks for opening the PR. I am running the code locally and I can only see a single card being active

image

**Comment by prabhuignoto** [comment]
@rawandeheliah thanks for opening the PR. I am running the code locally and I can only see a single card being active

image

**Comment by rawandeheliah** [comment]
yea, and the reason for that is I kept the default behavior as is , and if you want to turn on "show all cards" feature, add `showAllCards={true} ` to horizontal Chrono component in app-samples.tsx

**Comment by prabhuignoto** [comment]
@rawandeheliah 
we would also need the keyboard-based navigation working for the horizontal mode. is this something you are planning to include as part of this PR too. Thanks again for this.

**Comment by rawandeheliah** [comment]
You are welcome , 
well I have tried the horizontal mode and I can  navigate using arrow right and left , am I missing something ?
there is already a function handle the  keyboard-based navigation which is `handleKeySelection` in timeline.tsx file, which also takes care of horizontal mode .

**Comment by prabhuignoto** [comment]
> You are welcome , well I have tried the horizontal mode and I can navigate using arrow right and left , am I missing something ? there is already a function handling the keyboard-based navigation which is `handleKeySelection` in timeline.tsx file, which also takes care of horizontal mode .

Thanks, the navigation does seem to work. but I noticed the scroll is not smooth and i see a sudden jump. one other point in vertical mode, when you click on a card, the timeline is automatically scrolled and the clicked card is brought into focus. see below.

[issue](https://www.awesomescreenshot.com/video/6583633?key=8d5ba31f1cc257f19de4f5812699b62d)

**Comment by rawandeheliah** [comment]
> > You are welcome , well I have tried the horizontal mode and I can navigate using arrow right and left , am I missing something ? there is already a function handling the keyboard-based navigation which is `handleKeySelection` in timeline.tsx file, which also takes care of horizontal mode .
> 
> Thanks, the navigation does seem to work. but I noticed the scroll is not smooth and i see a sudden jump. one other point in vertical mode, when you click on a card, the timeline is automatically scrolled and the clicked card is brought into focus. see below. This behavior does not happen for the horizontal mode.
> 
> [issue](https://www.awesomescreenshot.com/video/6583633?key=8d5ba31f1cc257f19de4f5812699b62d)

Yea I hear you , am trying to solve the automatic scroll in horizontal mode , but it looks it needs some changes , in useNewScrollPosition file , so am working on that now ,"useNewScrollPosition"  is a little bit complicated, it has some complicated calculations .

**Comment by rawandeheliah** [comment]
the issue is here at timeline.tsx 
in lines 155-165
`useEffect(() => {
    const ele = timelineMainRef.current;
    if (!ele) {
      return;
    }
    if (mode === 'HORIZONTAL') {
      ele.scrollLeft = newOffSet;
    } else {
      ele.scrollTop = newOffSet;
    }
  }, [newOffSet]);`
  
  in horizontal mode , element scroll left is not updated , regardless of what new offset is sent to it ,
  any idea why that happens ?

**Comment by prabhuignoto** [comment]
hi @rawandeheliah can you sync your code with the master. I am refactoring some parts of the scroll functionality and i will take care of the offset issue.

can you give me access to your branch as well please if not done already

**Comment by rawandeheliah** [comment]
ok , it looks like I found a solution for **solving the offset** issue , changing the "ref" place will solve the problem 
, will push the code soon 

----
and sure I will sync with master .
----
about what u said earlier : "I noticed the scroll is not smooth and i see a sudden jump." -> this happens only in showing one card mode , 
do u think is better to show always all cards ? and neglect showing one card case ?
the reason this happens is because : I kept the code for showing all cards as is , and for showing only one card :  I just  changed the visibility to true for chosen one only , so when the second card is chosen which is place is on the middle , the first one is hidden , and the second one is shown , so u see it as a jump .

I can try to solve this , or we can simply make one scenario which is only showing all cards , 
tell me what do u think is better .

**Comment by rawandeheliah** [comment]
I've sent u access request for the branch

**Comment by rawandeheliah** [comment]
after merging with master I have those errors :

```
Module not found: Error: You attempted to import /Users/rawanddeheliah/repos/react-chrono/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

**Comment by rawandeheliah** [comment]
no worries I was able to solve the issue 

PS: about dimension for circle in horizontal mode , I see that u use dimension to determine width and height of circle ,  but still u didn't pass it from horizontal timeline to reach circle modal , to solve the issue for now :  I added dimension as a constant 20px .

**Comment by prabhuignoto** [comment]
> no worries I was able to solve the issue
> 
> PS: about dimension for circle in horizontal mode , I see that u use dimension to determine width and height of circle , but still u didn't pass it from horizontal timeline to reach circle modal , to solve the issue for now : I added dimension as a constant 20px .

thanks , I will take a look again at the PR

**Comment by prabhuignoto** [comment]
hi @rawandeheliah was checking the branch, great work 👍. I still see package.json is not sync with the master. was all of the changes from master synced alright. can you confirm. see below.

image

thanks

**Comment by rawandeheliah** [comment]
thank u , 
I fixed package.json , and synced it with master

**Comment by ctindogarus4f** [comment]
any updates on this? this is an important feature and I would be really happy to see it in master

**Comment by prabhuignoto** [comment]
@rawandeheliah  Thanks for resolving 

With the new change the timeline labels have been pushed down. is this something that was intended. It would be nice to have them over the circle.

Before

image


After

image

**Comment by rawandeheliah** [comment]
@prabhuignoto I see , I pushed the code and put it as before "title above circle"

**Comment by ctindogarus4f** [comment]
If you still work on this, can there be an `HORIZONTAL_ALTERNATING` mode as well?

**Comment by rawandeheliah** [comment]
@ctindogarus4f I am sorry , but for now I don't have time to work on `HORIZONTAL_ALTERNATING` mode , If I have time in future , sure will take a look .

**Comment by sandraa18** [comment]
Any updates on this? :)

**Comment by rawandeheliah** [comment]
@ctindogarus4f waiting for the author to merge .

**Comment by sandraa18** [comment]
@prabhuignoto is it possible to merge this? :)

**Comment by AminMkh** [comment]
@prabhuignoto I could also use this, could you merge

**Comment by prabhuignoto** [comment]
@AminMkh this feature is now available in the latest version. use `showAllCardsHorizontal` to display all cards in horizontal mode

**Pull request closed without merging**
