### PR TITLE
style: fix style with border-box

### LINKED ISSUE #269: The abnormal box model causes the overall style to be skewed to the right
image

When I change the box model of the DOM element it looks back to normal～

add as follow：

```css
xxx: {
   box-sizing: border-box;
}
```

image

### PR DESCRIPTION
**Pull request by bigbigDreamer**
### Additional context

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/prabhuignoto/react-chrono/blob/master/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (`fixes #269 `).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by bigbigDreamer** [comment]
#269 @prabhuignoto

**Comment by bigbigDreamer** [comment]
image

Now, Scroll bar displays normally.

**Comment by prabhuignoto** [comment]
@bigbigDreamer thanks for the opening PR. I am just wondering if we can limit the styles to just the timeline container. What do you think?

**Comment by bigbigDreamer** [comment]
image

In my local edge, The tests were passed. Please approval to try ci test. @prabhuignoto

**Comment by bigbigDreamer** [comment]
First bug had fixed! All tests were passed.

**Comment by prabhuignoto** [comment]
@bigbigDreamer looks great now. can you please remove the pnpm-lock .yaml file

**Comment by prabhuignoto** [comment]
@bigbigDreamer just merged. Thanks for the fix 👍

**Comment by prabhuignoto** [comment]
@all-contributors please add @bigbigDreamer for code

**Pull request merged**
