### PR TITLE
Change order in object.assign to prefer user provided props

### PR DESCRIPTION
**Pull request by ajeetshah**
Change order in object.assign to prefer user provided props over default ones

### CODE REVIEW

**Comment by prabhuignoto** [comment]
Hi @ajeetshah,
Welcome to react-chrono. Thanks for raising a PR.

`id`, `visible` and `active` are internal properties and the consumers of the component  should not manually pass this.

README has a clear instruction on list of allowed props for each timelineItem. https://github.com/prabhuignoto/react-chrono#timeline-item-model.

i am happy to help if there is a specific problem that you are facing while using the component.

**Comment by ajeetshah** [comment]
I was trying to mark the last item as `active` at first render. How can I do that?

**Comment by prabhuignoto** [comment]
Thanks for your response. Can you please elaborate the UX use case for selecting the last item on load. Timelines are essentially sequential in nature and selecting last event/item on load goes against this.

**Comment by ajeetshah** [comment]
Let's say we want to build something like Amazon "order status". So the timeline goes like: 1.Ordered, 2.Payment done, 3.Dispatched, 4.Out for delivery. And today the status is "out for delivery". Here, we would like to show the last item i.e. "4. Out for delivery" to be shown as active. Isn't it?

**Comment by prabhuignoto** [comment]
The component right now supports only static timeline and the active is used internally for styling purposes only . Progress tracking is not something the component can handle right now and was built for ,but it would definitely be a great addition.
 
I can definitely see the component being used for live progress tracking scenarios and it's great you brought it up.

I am going to add a separate backlog item for this.

I had a look at the pr again now, Both the selection and auto scroll are failing when I select a timeline item.

**Pull request closed without merging**
